### ISSUE TITLE
display

### ISSUE THREAD

**Issue by johnwcowan** [jrincayc/r7rs-pico-spec#12]
I know Pico isn't supposed to have side effects, but as long as there are no read operations, `display` (to stdout only) is harmless and allows people to write programs that  generate results other than those that can be produced by the REPL.

**Comment by jrincayc** [comment]
Hm, I suppose I could define `<program> -> <expression or definition or output>+` ... `<output> -> (display expression) | (newline)` which would let display and newline be used at the toplevel.

**Comment by jrincayc** [comment]
(As in I don't mind the toplevel being made into a sorta I/O monad, but I would rather not allow expressions to have output.)

**Comment by johnwcowan** [comment]
I don't think that's necessary, because `display` and `newline` are basically no-ops from the point of view of the Pico machine.  You'd want to add `begin`, which just expands to `lambda`, so that things come out in the right order.

But maybe I don't understand.  Can you give an example?

**Comment by jrincayc** [comment]
Hm, it might be too late for me to be writing this right now (so apologies if this doesn't make sense).  Pico scheme order is completely up to the implementation, and can't really be detected.  This would be a syntax error: `((lambda a (display 1) (display 2) a) 4)`  (Even if a function display was defined because `lambda` in pico only takes one expression)  There is the whole permute and unpermute in r7rs small, so I think that the order of say: `(cons (display 1) (display 2))` is unspecified.  So adding `begin` would require allowing multiple expressions in `lambda`.

**Comment by jrincayc** [comment]
I think having `display` as an expression would break no-side effects too much. However, without some form of output, programs are rather useless (as pointed out in https://github.com/jrincayc/r7rs-pico-spec/issues/12#issue-1352911502 ), so my conclusion is that allowing them at the toplevel is a good idea:
`<program> -> <expression or definition or io>+` ... `<io> -> (display <expression>) | (newline)` 
Since implementations already have to support an external representation, I don't think the additional burden is too much for adding `display` and `newline`  for programs.  Since the program can concatenate everything into one final output and pass it back to toplevel, this is sufficient to allow turing complete programs (assuming that the input was put into a define at the start).  pico scheme implementations would of course be free to allow `display` to be used as an expression if they wish to allow that form of side effect.

I think a proper way of incorporating IO into pico scheme programs with side-effect-free expressions is more of a research project than I want to do.  One thought of mine for the future would be to have something like `<command> -> <expression> | <define> | <io>' and add  `begin` and `do` that take commands.

I don't think I will add `<io> -> (define <identifier> (read))` to pico scheme tho' I may suggest that as an expansion that an implementation could add.

It might also be worth considering adding `write-u8` as part of this addition. However, since there is no way to loop at toplevel, this might not be that useful.

(I did consider just removing programs and only having a REPL, but I think programs are a useful concept, and some output form is needed for them.)

Thank you for this suggestion.
