### ISSUE TITLE
clarify use of define in internal definitions

### ISSUE THREAD

**Issue by jobol** [jrincayc/r7rs-pico-spec#44]
It is not clear from reading 5.2.2 if the variable is defined in the environment of its evaluation or not.

The section 5.2.1 specifically explains the case for defining recursive lambdas.

Is it possible to do the same for locally defined lambda using define?

Probably yes but it is not clear.

**Comment by jrincayc** [comment]
I agree that it could be more clear.  From the denotational semantics, if "ε ∈ F" is the only case where a variable is defined in the environment of its evaluation.

What kind of code were you thinking of for this?
The following would be an error is R7RS (not necessarily signaled), but by the denotational semantics (assuming I got them the way I wanted) it should result in `a` being 4 in Pico Scheme:
```scheme
(define a (+ 1 1))
(define a (+ a a))
``` 
but this is because a `define`  put a variable in all statements that are after the define in the body.

**Comment by jrincayc** [comment]
Yes, it is possible to do a recursive function anywhere you can use a define.  For what it is worth, there is no straight forward way to do mutually recursive functions (a calls b, b calls a).  (I think (define a ...) (define b ...) (define a ...) would work but I am not sure I recommend doing that).

I will look at sections 5.2.1 and 5.2.2 and see if I can make some of this more clear in a pull request.

**Comment by jobol** [comment]
I agree that mutually recursive function are not straight forward with pr7 and also agree that your trick is ugly.

While checking for how to improve  5.2.1 and 5.2.2, also mentionning the restriction on mutually recursive functions would help.

**Comment by jrincayc** [comment]
How about this way to do mutually recursive:
```scheme
(define a
  (lambda (x)
    (define b
      (lambda (x) (a (- x 1))))
    (if (< x 1) 0
	(b (- x 1)))))
(a 3)
```
